config/routes.rb
# -*- encoding : utf-8 -*-

LiberdadeBr::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

#= 1. user routes ==============================================================
  devise_for :users

#= 2. pages ====================================================================
  get "/contato" => "site#contact", :as => :contact
  post "/contato" => "site#send_contact", :as => :send_contact
  get '/about' => 'site#about', :as => :about
  get '/faq' => 'site#faq', :as => :faq
  get '/financers' => 'site#financers', :as => :financers

#= 3. Post evaluation routes ===================================================
  post "/admin/post/:post_id/approve/:user_id" => "posts#approve", :as => :approve_post
  post "/admin/post/:post_id/reprove/:user_id" => "posts#reprove", :as => :reprove_post
  post "/admin/post/:post_id/abstention/:user_id" => "posts#abstention", :as => :abstention_post

#= 4. Author ===================================================================
  get '/posts/author/:id' => 'posts#per_author', :as => :posts_author

#= 5. Blog =====================================================================
  get '/posts/blog/:id' => 'posts#per_blog', :as => :posts_blog

#= 6. Category =================================================================
  get '/posts/category/:id' => 'posts#per_category', :as => :posts_category

#= 7. Post =====================================================================
  resources :posts, :only => [:index, :show, :new]
  post "/posts" => "posts#index", :as => :posts
  post '/posts/send' => 'posts#send_post', :as => :send_post

#= 8. Events and Opportunities =================================================
  get '/eventos-e-oportunidades' => 'site#events_and_opportunities', :as => :events_and_opportunities

#= 9. Events ===================================================================
  get '/eventos' => 'events#index', :as => :events
  get '/evento/:id' => 'events#show', :as => :event

#= 10. Opportunities ===========================================================
  get '/oportunidades' => 'opportunities#index', :as => :opportunities
  get '/oportunidade/:id' => 'opportunities#show', :as => :opportunity

#= 11. Feed ====================================================================
  get '/feed' => 'posts#feed', :as => :feed, :defaults => { :format => 'atom' }

#= 12. Donate ==================================================================
  get '/doacao' => 'site#donate', :as => :donate

  root :to => 'site#index'
end

app/views/widgets/_advertising.html.erb
<% if configuration.ad_published %>
  <div class="sidebar_box_wrapper" id="ad_box">
    <div class="sidebar_box">
      <p class="buttom">
        <%= link_to 'Acesse agora', configuration.ad_url,
          :target => ('_blank' if configuration.ad_new_tab) %>
      </p>
    </div>
  </div>

  <style type="text/css">
    #ad_box .sidebar_box {
      background: url("<%= configuration.ad_image.url(:normal) %>") no-repeat center;
    }
  </style>
<% end %>

app/views/widgets/_blog.html.erb
<% if not blog.nil? and not blog.description.blank? %>
  <div class="sidebar_panel">
    <div class="sidebar_box">
      <h3><%= blog.name %></h3>

      <p>
        <% if blog.image.exists? %>
          <%= image_tag blog.image.url(:thumb), :alt => blog.name,
            :size => '150x150', :class => 'image_box' %>
        <% end %>
        <%= blog.description.html_safe %>
      </p>

      <p class="buttom">
        <%= link_to 'Veja mais posts deste blog', posts_blog_path(blog) %>
      </p>
    </div>
  </div>
<% end %>

app/views/widgets/_events.html.erb
<%
  events = Event.where('published = ? AND date >= ?', true, Date.today).
    order('date').limit(5)
  title ||= nil
%>

<% unless events.empty? %>
  <div class="sidebar_panel" id="events_panel">
    <h3><%= link_to title.nil? ? 'Eventos' : title, events_path %></h3>

    <ul>
      <% events.each do |e| %>
        <li>
          <span class="date"><%= e.date.strftime('%d/%m') %></span>
          <%= link_to e.name, event_path(e) %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/widgets/_facebook_likebox.html.erb
<% if configuration.facebook_like_goal and configuration.facebook %>
  <% fb_id = configuration.facebook.split('/').last %>

  <div class="sidebar_box_wrapper" id="facebook_box">
    <div class="sidebar_box">
      <h3>Ajude-nos a conseguir <%= configuration.facebook_like_goal %> fãs no Facebook</h3>

      <div class="facebook_progress_bar" data-id="<%= fb_id %>" data-goal="<%= configuration.facebook_like_goal %>">
        <p><span>Carregando...</span></p>
      </div>

      <div class="facebook_like_iframe">
        <iframe src="https://www.facebook.com/plugins/like.php?href=<%= configuration.facebook %>" scrolling="no" frameborder="0" style="border:none; width:300px; height:65px"></iframe>
      </div>
    </div>
  </div>
<% end %>

app/views/widgets/_opportunities.html.erb
<%
  opportunities = Opportunity.where('published = ?', true).
    order('created_at DESC').limit(5)
  title ||= nil
%>

<% unless opportunities.empty? %>
  <div class="sidebar_panel" id="opportunities_panel">
    <h3><%= link_to title.nil? ? 'Oportunidades' : title, opportunities_path %></h3>

    <ul>
      <% opportunities.each do |o| %>
        <li><%= link_to o.title, opportunity_path(o) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/widgets/_posts.html.erb
<%
  posts = @post.similar[0..4]
%>

<% unless posts.empty? %>
  <div class="sidebar_panel">
    <h3><%= link_to 'Posts relacionados', posts_path %></h3>

    <ul>
      <% posts.each do |p| %>
        <li><%= link_to p.title, post_path(p.id) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/widgets/_send_post.html.erb
<% send_post_page = Page.get_page(:send_post) %>
<% if send_post_page and send_post_page.published? %>
  <div class="sidebar_box_wrapper" id="submit_post_box">
    <div class="sidebar_box">
      <h3>Envie seu artigo</h3>

      <p>Você gosta de escrever sobre a causa da liberdade mas não tem um blog?
      Envie o seu texto para nós!</p>

      <p class="buttom">
        <%= link_to 'Envie agora', new_post_path %>
      </p>
    </div>
  </div>
<% end %>

app/views/widgets/_twitter.html.erb
<% unless configuration.twitter.blank? %>
  <div class="sidebar_box_wrapper" id="twitter_box">
    <div class="sidebar_box">
      <h3>Liberdade.BR no Twitter</h3>

      <div class="iframe">
        <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
        <script type="text/javascript">
          new TWTR.Widget({
            version: 2,
            type: 'profile',
            rpp: 4,
            interval: 30000,
            width: 310,
            height: 300,
            theme: {
              shell: {
                background: '#ffffff',
                color: '#000000'
              },
              tweets: {
                background: '#ffffff',
                color: '#444444',
                links: '#5599ff'
              }
            },
            features: {
              scrollbar: false,
              loop: false,
              live: false,
              behavior: 'all'
            }
          }).render().setUser("<%= configuration.twitter.split('/').last %>").start();
        </script>
      </div>
    </div>
  </div>
<% end %>