config/routes.rb
# -*- encoding : utf-8 -*-

LiberdadeBr::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

#= 1. user routes ==============================================================
  devise_for :users

#= 2. pages ====================================================================
  get "/contato" => "site#contact", :as => :contact
  post "/contato" => "site#send_contact", :as => :send_contact
  get '/about' => 'site#about', :as => :about
  get '/faq' => 'site#faq', :as => :faq
  get '/financers' => 'site#financers', :as => :financers

#= 3. Post evaluation routes ===================================================
  post "/admin/post/:post_id/approve/:user_id" => "posts#approve", :as => :approve_post
  post "/admin/post/:post_id/reprove/:user_id" => "posts#reprove", :as => :reprove_post
  post "/admin/post/:post_id/abstention/:user_id" => "posts#abstention", :as => :abstention_post

#= 4. Author ===================================================================
  get '/posts/author/:id' => 'posts#per_author', :as => :posts_author

#= 5. Blog =====================================================================
  get '/posts/blog/:id' => 'posts#per_blog', :as => :posts_blog

#= 6. Category =================================================================
  get '/posts/category/:id' => 'posts#per_category', :as => :posts_category

#= 7. Post =====================================================================
  resources :posts, :only => [:index, :show, :new]
  post "/posts" => "posts#index", :as => :posts
  post '/posts/send' => 'posts#send_post', :as => :send_post

#= 8. Events and Opportunities =================================================
  get '/eventos-e-oportunidades' => 'site#events_and_opportunities', :as => :events_and_opportunities

#= 9. Events ===================================================================
  get '/eventos' => 'events#index', :as => :events
  get '/evento/:id' => 'events#show', :as => :event

#= 10. Opportunities ===========================================================
  get '/oportunidades' => 'opportunities#index', :as => :opportunities
  get '/oportunidade/:id' => 'opportunities#show', :as => :opportunity

#= 11. Feed ====================================================================
  get '/feed' => 'posts#feed', :as => :feed, :defaults => { :format => 'atom' }

#= 12. Donate ==================================================================
  get '/doacao' => 'site#donate', :as => :donate

  root :to => 'site#index'
end

app/controllers/site_controller.rb
# -*- encoding : utf-8 -*-

class SiteController < ApplicationController

  def index
    @banners = Banner.where('published = ?', true).reverse
    @search = Post.published.order('approved_at DESC').
      search(params[:q])
    @posts = @search.result
    @posts = @posts.uniq.limit(6)
  end

  def events_and_opportunities
    @events = Event.where('published = ? AND date >= ?', true, Date.today).
      order('date')
    @opportunities = Opportunity.where('published = ?', true).
      order('created_at')
  end

  # CONTACT BEGIN

  def contact
    @contact = Page.where('indicator = ?', Page::PAGES[:contact]).first
    @contact_form = Contact.new

    raise ActionController::RoutingError.new('Not Found') unless @contact.published
  end

  def send_contact
    @contact = Page.where('indicator = ?', Page::PAGES[:contact]).first
    @contact_form = Contact.new(params[:contact])

    if verify_recaptcha(:model => @contact_form, :message => 'Você digitou palavas erradas no reCAPTCHA.')
      if @contact_form.save
        redirect_to(contact_path, :notice => 'Mensagem enviada com sucesso.')
      else
        render :action => :contact
      end
    else
      @contact_form.valid?
      @recaptcha_error = 'Você digitou palavras incorretas. Tente novamente.'
      render :action => :contact
    end
  end

  # CONTACT END

  def about
    @about = Page.where('indicator = ?', Page::PAGES[:about]).first

    raise ActionController::RoutingError.new('Not Found') unless @about.published
  end

  def faq
    @faq = Page.where('indicator = ?', Page::PAGES[:faq]).first

    raise ActionController::RoutingError.new('Not Found') unless @faq.published
  end

  def financers
    @financers = Page.where('indicator = ?', Page::PAGES[:financers]).first

    raise ActionController::RoutingError.new('Not Found') unless @financers.published
  end

  def donate
    @donate = Page.where('indicator = ?', Page::PAGES[:donate]).first

    raise ActionController::RoutingError.new('Not Found') unless @donate.published
  end
end

app/views/site/about.html.erb
<%= content_for :page_title do @about.title end %>

<%= content_for :page_id do 'about' end %>

<%= content_for :content do %>
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content_shadow"></div>
    <div id="content_gradiente"></div>

    <div id="content">
      <div id="content_header">
        <ul class="breadcrumbs">
          <li><%= link_to 'Início', root_path %></li>
          <li><span><%= @about.title %></span></li>
        </ul>

        <hr />

        <div class="header">
          <h2><%= @about.title %></h2>
        </div>
      </div>

      <div id="main_content">
        <div class="post">
          <%= @about.content.html_safe if @about.content %>
        </div>
      </div>

      <div id="sidebar">
        <%= render :partial => 'widgets/facebook_likebox' %>
        <%= render :partial => 'widgets/twitter' %>
      </div>

    </div>
  </div>
  <!-- CONTENT END -->

<% end %>

app/views/site/contact.html.erb
<%= content_for :page_title do @contact.title end %>

<%= content_for :page_id do 'contact' end %>

<%= content_for :content do %>
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content_shadow"></div>
    <div id="content_gradiente"></div>

    <div id="content">
      <div id="content_header">
        <ul class="breadcrumbs">
          <li><%= link_to 'Início', root_path %></li>
          <li><span><%= @contact.title %></span></li>
        </ul>

        <hr />

        <div class="header">
          <h2><%= @contact.title %></h2>
        </div>
      </div>

      <div id="main_content">
        <div class="post">
          <%= @contact.content.html_safe if @contact.content %>
        </div>

        <%= simple_form_for(@contact_form, :url => send_contact_path) do |f| %>
          <%= content_tag(:p, notice, :class => 'notice') if notice %>

          <div class="fields">
            <%= f.input :name %>
            <%= f.input :email %>
            <%= f.input :message, :as => :text %>
            <%= recaptcha_tags :display => {:theme => 'red' , :tabindex => '8' } %>
            <% if @recaptcha_error.present? %>
              <div class="input"><span class="error"><%= @recaptcha_error %></span></div>
            <% end %>
          </div>

          <div class="actions">
            <p class="buttom"><%= f.button :submit, 'Enviar mensagem' %></p>
          </div>
        <% end %>
      </div>

      <div id="sidebar">
        <%= render :partial => 'widgets/facebook_likebox' %>
        <%= render :partial => 'widgets/twitter' %>
      </div>

    </div>
  </div>
  <!-- CONTENT END -->
<% end %>

app/views/site/donate.html.erb
<%= content_for :page_title do @donate.title end %>

<%= content_for :page_id do 'donate' end %>

<%= content_for :content do %>
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content_shadow"></div>
    <div id="content_gradiente"></div>

    <div id="content">
      <div id="content_header">
        <ul class="breadcrumbs">
          <li><%= link_to 'Início', root_path %></li>
          <li><span><%= @donate.title %></span></li>
        </ul>

        <hr />

        <div class="header">
          <h2><%= @donate.title %></h2>
        </div>
      </div>

      <div id="main_content">
        <div class="post">
          <%= @donate.content.html_safe if @donate.content %>
        </div>
      </div>

      <div id="sidebar">
        <%= render :partial => 'widgets/facebook_likebox' %>
        <%= render :partial => 'widgets/twitter' %>
      </div>

    </div>
  </div>
  <!-- CONTENT END -->

<% end %>

app/views/site/events_and_opportunities.html.erb
<%= content_for :page_title do 'Eventos e oportunidades' end %>

<%= content_for :page_id do 'events_and_opportunities' end %>

<%= content_for :content do %>
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content_shadow"></div>
    <div id="content_gradiente"></div>

    <div id="content">
      <div id="content_header">
        <ul class="breadcrumbs">
          <li><%= link_to 'Início', root_path %></li>
          <li><span>Eventos e oportunidades</span></li>
        </ul>

        <hr />

        <div class="header">
          <h2>Eventos e oportunidades</h2>
        </div>
      </div>

      <div id="main_content">
        <% unless @events.limit(6).empty? %>
          <h2>Eventos em destaque</h2>

          <ul class="events_list">
            <% @events.limit(6).each do |e| %>
              <li>
                <div class="date">
                  <p>
                    <span class="day"><%= e.date.strftime('%d') %></span>
                    <span class="month"><%= localize e.date, :format => '%b' %></span>
                  </p>
                </div>

                <div class="event_content">
                  <h3><%= link_to e.name, event_path(e) %></h3>

                  <% if e.image.exists? %>
                    <p class="image">
                      <%= image_tag e.image.url(:event_list_image),
                        :alt => e.name, :size => '120x120' %>
                    </p>
                  <% end %>

                  <% if e.description %>
                    <p class="resume">
                      <%= smart_truncate(e.description, 200) %>
                    </p>
                  <% end %>

                  <p class="more"><%= link_to 'Mais informações', event_path(e) %></p>
                </div>
              </li>
            <% end %>
          </ul>
        <% end %>

        <% if @events.length > 6 %>
          <hr />

          <p class="buttom"><%= link_to 'Mais eventos', events_path %></a></p>
        <% end %>
      </div>

      <div id="sidebar">
        <% unless @opportunities.limit(6).empty? %>
          <h2>oportunidades</h2>

          <ul class="opportunities_list">
            <% @opportunities.limit(6).each do |o| %>
              <li>
                <h3><%= link_to o.title, opportunity_path(o) %></h3>

                <% if o.content %>
                  <p class="resume">
                    <%= smart_truncate(o.content, 200) %>
                  </p>
                <% end %>

                <p class="more"><%= link_to 'Mais informações', opportunity_path(o) %></p>
              </li>
            <% end %>
          </ul>
        <% end %>

        <% if @opportunities.length > 6 %>
          <hr />

          <p class="buttom"><%= link_to 'Mais oportunidades', opportunities_path %></a></p>
        <% end %>

        <div class="sidebar_detail"></div>
      </div>

    </div>
  </div>
  <!-- CONTENT END -->

<% end %>

app/views/site/faq.html.erb
<%= content_for :page_title do @faq.title end %>

<%= content_for :page_id do 'faq' end %>

<%= content_for :content do %>
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content_shadow"></div>
    <div id="content_gradiente"></div>

    <div id="content">
      <div id="content_header">
        <ul class="breadcrumbs">
          <li><%= link_to 'Início', root_path %></li>
          <li><span><%= @faq.title %></span></li>
        </ul>

        <hr />

        <div class="header">
          <h2><%= @faq.title %></h2>
        </div>
      </div>

      <div id="main_content">
        <div class="post">
          <%= @faq.content.html_safe if @faq.content %>
        </div>
      </div>

      <div id="sidebar">
        <%= render :partial => 'widgets/facebook_likebox' %>
        <%= render :partial => 'widgets/twitter' %>
      </div>

    </div>
  </div>
  <!-- CONTENT END -->

<% end %>

app/views/site/financers.html.erb
<%= content_for :page_title do @financers.title end %>

<%= content_for :page_id do 'financers' end %>

<%= content_for :content do %>
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content_shadow"></div>
    <div id="content_gradiente"></div>

    <div id="content">
      <div id="content_header">
        <ul class="breadcrumbs">
          <li><%= link_to 'Início', root_path %></li>
          <li><span><%= @financers.title %></span></li>
        </ul>

        <hr />

        <div class="header">
          <h2><%= @financers.title %></h2>
        </div>
      </div>

      <div id="main_content">
        <div class="post">
          <%= @financers.content.html_safe if @financers.content %>
        </div>
      </div>

      <div id="sidebar">
        <%= render :partial => 'widgets/facebook_likebox' %>
        <%= render :partial => 'widgets/twitter' %>
      </div>

    </div>
  </div>
  <!-- CONTENT END -->

<% end %>

app/views/site/index.html.erb
<%= content_for :page_title do 'Principal' end %>

<%= content_for :page_id do 'index' end %>

<%= content_for :banner do %>

  <% unless @banners.empty? %>
    <!-- BANNER BEGIN -->

    <style>
      <% @banners.each_with_index do |b, i| %>
        #banner_<%= i %> {
          background: url("<%= b.image.url %>") no-repeat center;
        }
      <% end %>
    </style>

    <div id="banner_wrapper" <%= 'class="no_slide"'.html_safe if @banners.length == 1 %>>
      <div id="banner">

        <ul class="images">
          <% @banners.each_with_index do |b, i| %>
            <li id="banner_<%= i %>"></li>
          <% end %>
        </ul>

        <div class="infos_wrapper">
          <div class="infos">
            <ul>
              <% @banners.each do |b| %>
                <li>
                  <% if b.link.blank? %>
                    <h3><%= b.title %></h3>

                    <%= content_tag :h4, b.description if b.description %>

                  <% else %>
                    <% if b.open_in_new_tab %>
                      <h3><%= link_to b.title, b.link, :target => '_blank' %></h3>

                      <%= content_tag :h4, b.description if b.description %>

                      <p class="buttom"><%= link_to 'Leia mais', b.link, :target => '_blank'  %></p>
                    <% else %>
                      <h3><%= link_to b.title, b.link %></h3>

                      <%= content_tag :h4, b.description if b.description %>

                      <p class="buttom"><%= link_to 'Leia mais', b.link %></p>
                    <% end %>
                  <% end %>
                </li>
              <% end %>
            </ul>

            <p class="controls">
              <% @banners.length.times do |i| %>
                <span <%= 'class="active"'.html_safe if i == 0 %>><%= i %></span>
              <% end %>
            </p>
          </div>
        </div>

      </div>
    </div>
    <!-- BANNER END -->
  <% end %>

<% end %>

<%= content_for :content do %>
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content_shadow"></div>
    <div id="content_gradiente"></div>

    <div id="content">

      <div id="main_content">
        <%= render :partial => 'posts/search_form', :locals => { :search => @search } %>

        <%= render :partial => 'posts/posts', :locals => { :posts => @posts } %>

        <% unless @posts.length < 6 %>
          <hr />

          <p class="buttom"><%= link_to 'Mais postagens', posts_path(:page => 2) %></a></p>
        <% end %>
      </div>

      <div id="sidebar">
        <%= render :partial => 'widgets/send_post' %>
        <%= render :partial => 'widgets/advertising' %>
        <%= render :partial => 'widgets/facebook_likebox' %>
        <%= render :partial => 'widgets/events' %>
        <%= render :partial => 'widgets/opportunities' %>
      </div>

    </div>
  </div>
  <!-- CONTENT END -->

<% end %>