config/routes.rb
# -*- encoding : utf-8 -*-

LiberdadeBr::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

#= 1. user routes ==============================================================
  devise_for :users

#= 2. pages ====================================================================
  get "/contato" => "site#contact", :as => :contact
  post "/contato" => "site#send_contact", :as => :send_contact
  get '/about' => 'site#about', :as => :about
  get '/faq' => 'site#faq', :as => :faq
  get '/financers' => 'site#financers', :as => :financers

#= 3. Post evaluation routes ===================================================
  post "/admin/post/:post_id/approve/:user_id" => "posts#approve", :as => :approve_post
  post "/admin/post/:post_id/reprove/:user_id" => "posts#reprove", :as => :reprove_post
  post "/admin/post/:post_id/abstention/:user_id" => "posts#abstention", :as => :abstention_post

#= 4. Author ===================================================================
  get '/posts/author/:id' => 'posts#per_author', :as => :posts_author

#= 5. Blog =====================================================================
  get '/posts/blog/:id' => 'posts#per_blog', :as => :posts_blog

#= 6. Category =================================================================
  get '/posts/category/:id' => 'posts#per_category', :as => :posts_category

#= 7. Post =====================================================================
  resources :posts, :only => [:index, :show, :new]
  post "/posts" => "posts#index", :as => :posts
  post '/posts/send' => 'posts#send_post', :as => :send_post

#= 8. Events and Opportunities =================================================
  get '/eventos-e-oportunidades' => 'site#events_and_opportunities', :as => :events_and_opportunities

#= 9. Events ===================================================================
  get '/eventos' => 'events#index', :as => :events
  get '/evento/:id' => 'events#show', :as => :event

#= 10. Opportunities ===========================================================
  get '/oportunidades' => 'opportunities#index', :as => :opportunities
  get '/oportunidade/:id' => 'opportunities#show', :as => :opportunity

#= 11. Feed ====================================================================
  get '/feed' => 'posts#feed', :as => :feed, :defaults => { :format => 'atom' }

#= 12. Donate ==================================================================
  get '/doacao' => 'site#donate', :as => :donate

  root :to => 'site#index'
end

app/models/post.rb
# -*- encoding : utf-8 -*-
class Post < ActiveRecord::Base
  belongs_to :blog

  has_many :author_posts
  has_many :authors, :through => :author_posts
  has_many :category_posts
  has_many :categories, :through => :category_posts
  has_many :post_evaluations, :dependent => :destroy
  has_many :users, :through => :post_evaluations

  CRITERION_FOR_PUBLICATION = {
    :by_moderation => 0,
    :always_published => 1,
    :always_unpublished => 2
  }

  validates_presence_of :title
  validates_presence_of :authors, :if => lambda { self.blog.nil? }
  validates_presence_of :content, :if => lambda { self.blog.nil? }

  after_validation :check_rates_to_publish, :if => lambda {
    self.approval_rate_changed? or self.reproval_rate_changed? or self.abstention_rate_changed?
  }

  before_create :set_default_published_at, :if => lambda { self.published_at.blank? }
  before_save :set_default_approved_at, :if => lambda { self.approved_at.blank? and published_by_admin? }

  before_validation :set_moderator_counter, :on => :create

  attr_accessible :title, :url, :content, :published_at, :blog, :authors,
     :author_ids, :categories,:category_ids, :blog_id, :approved_at,
     :evaluations, :evaluation_ids, :post_evaluations, :post_evaluation_ids,
     :approval_rate, :reproval_rate, :hilight, :evaluations_pretty,
     :user_evaluation, :moderator_conter, :criterion_for_publication,
     :last_evaluation_date, :abstention_rate

  def self.create_from_feed_entry(entry, blog)
    categories_to_match = Configuration.last.categories.map(&:name)
    entry_categories = entry.categories.map(&:downcase_with_accents)

    if (entry_categories & categories_to_match).any? or categories_to_match.empty?
      categories = []
      entry.categories.each do |name|
        categories << Category.get_or_create_by_name(name)
      end

      authors = []

      if entry.author.nil?
        authors << Author.get_or_create_by_name(blog.name)
      else
        entry.author.split(',').each do |name|
          authors << Author.get_or_create_by_name(name.strip)
        end
      end

      Post.create!(
        :title => entry.title,
        :url => entry.url,
        :content => entry.content.blank? ? entry.summary : entry.content,
        :published_at => entry.published,
        :categories => categories,
        :authors => authors,
        :blog => blog
      )
    end
  end

  def self.build_from_new_post_page(params)
    categories = []
    unless params[:categories].nil?
      params[:categories].split(',').each do |name|
        categories << Category.get_or_create_by_name(name.strip)
      end
    end

    authors = []
    unless params[:authors].nil?
      params[:authors].split(',').each do |name|
        authors << Author.get_or_create_by_name(name.strip)
      end
    end

    post = Post.new(
      :title => params[:title],
      :content => params[:content],
      :categories => categories,
      :authors => authors
    )
    return post
  end

  def evaluations_count
    "#{self.post_evaluations.count}/#{self.moderator_counter}"
  end

  def check_rates_to_publish
    if self.approval_rate >= 20.0 and self.reproval_rate < 20.0
      self.published = true
      self.approved_at = Date.today if self.approved_at.blank?
    else
      self.published = false
      self.approved_at = nil
    end
  end

  def update_evaluation_rates
    self.update_moderator_counter
    approvals = self.post_evaluations.
      where('approve = ?', PostEvaluation::OPTIONS[:approve]).count

    reprovals = self.post_evaluations.
      where('approve = ?', PostEvaluation::OPTIONS[:reprove]).count

    abstentions = self.post_evaluations.
      where('approve = ?', PostEvaluation::OPTIONS[:abstention]).count

    users = self.moderator_counter
    self.update_attributes(
      :approval_rate => (approvals.to_f/users.to_f*100).round(1),
      :reproval_rate => (reprovals.to_f/users.to_f*100).round(1),
      :abstention_rate => (abstentions.to_f/users.to_f*100).round(1),
      :last_evaluation_date => DateTime.now
    )
  end

  def user_evaluation
  end

  def evaluations_pretty
    "Aprovação: #{self.approval_rate}% / Reprovação: #{self.reproval_rate}% / Abstenções: #{self.abstention_rate}%"
  end

  def set_moderator_counter
    self.moderator_counter = User.count
  end

  def update_moderator_counter
    if self.post_evaluations.count > self.moderator_counter
      self.moderator_counter = self.post_evaluations.count
    end
  end

  def published_by_admin?
    self.criterion_for_publication == CRITERION_FOR_PUBLICATION[:always_published]
  end

  def unpublished_by_admin?
    self.criterion_for_publication == CRITERION_FOR_PUBLICATION[:always_unpublished]
  end

  def published_by_moderation?
    self.criterion_for_publication == CRITERION_FOR_PUBLICATION[:by_moderation]
  end

  def criterion_for_publication_enum
    { 'Avaliado pelos moderadores' => CRITERION_FOR_PUBLICATION[:by_moderation],
      'Sempre publicado' => CRITERION_FOR_PUBLICATION[:always_published],
      'Sempre despublicado' => CRITERION_FOR_PUBLICATION[:always_unpublished] }
  end

  def self.published
    Post.where('published = ? and criterion_for_publication <> ? or criterion_for_publication = ?',
      true, CRITERION_FOR_PUBLICATION[:always_unpublished], CRITERION_FOR_PUBLICATION[:always_published])
  end

  def able_to_publish?
    self.published_by_admin? or (self.published_by_moderation? and self.published)
  end

  def set_default_published_at
    self.published_at = Date.today
  end

  def set_default_approved_at
    self.approved_at = Date.today
  end

  def similar
    Post.published.order('published_at DESC').select { |p| (p.categories & self.categories).any? and p != self }
  end
end

app/controllers/posts_controller.rb
# -*- encoding : utf-8 -*-
class PostsController < ApplicationController

  before_filter :check_user, :only => [:approve, :reprove]
  before_filter :set_return_to_admin_url, :if => lambda { current_user }, :only => [:show]

  def rss
    @posts = Post.published.order('approved_at DESC')

    respond_to do |format|
       format.rss { render :layout => false }
    end
  end

  def feed
    # this will be the name of the feed displayed on the feed reader
    @title = "Liberdade.br"

    # the news items
    @posts = Post.published.order('approved_at DESC').limit(10)

    # this will be our Feed's update timestamp
    @updated = @posts.first.approved_at unless @posts.empty?

    respond_to do |format|
      format.atom { render :layout => false }

      # we want the RSS feed to redirect permanently to the ATOM feed
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end


  def index
    @search = Post.published.order('approved_at DESC').search(params[:q])
    @posts = @search.result
    @posts = @posts.uniq.page(params[:page]).per(6)
    @posts.reload
  end

  def new
    @page = Page.where('indicator = ?', Page::PAGES[:send_post]).first
    @post = Post.new

    raise ActionController::RoutingError.new('Not Found') unless @page.published
  end


  def send_post
    @page = Page.where('indicator = ?', Page::PAGES[:send_post]).first

    @post = Post.build_from_new_post_page(params[:post])
    @authors_input_value = @post.authors.map(&:name).join(', ')
    @categories_input_value = @post.categories.map(&:name).join(', ')

    if verify_recaptcha(:model => @post,
      :message => 'Você digitou palavas erradas no reCAPTCHA.')

      if @post.save
        flash[:notice] = 'Post enviado com sucesso. Ele será avaliado
          pelos moderadores antes de ser publicado no site.'

        redirect_to :action => 'new'
      else
        render :action => 'new'
      end
    else
      @post.valid?
      @recaptcha_error = 'Você digitou palavras incorretas. Tente novamente.'
      render :action => 'new'
    end
  end

  def show
    @post = Post.find(params[:id])

    if current_user
      @evaluation = PostEvaluation.where('user_id = ? AND post_id = ?',
        current_user, @post.id).first
      @voted_approve = @evaluation.try(:approve)
    end

    unless @post.able_to_publish? or current_user
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def per_author
    @search = Post.published.order('approved_at DESC').search(params[:q])
    @author = Author.find(params[:id])
    @posts = @author.published_posts.uniq.page(params[:page]).per(6)
    @posts.reload
    render :index
  end

  def per_blog
    @search = Post.published.order('approved_at DESC').search(params[:q])
    @blog = Blog.find(params[:id])
    @posts = @blog.published_posts.uniq.page(params[:page]).per(6)
    @posts.reload
    render :index
  end

  def per_category
    @search = Post.published.order('approved_at DESC').search(params[:q])
    @category = Category.find(params[:id])
    @posts = @category.published_posts.uniq.page(params[:page]).per(6)
    @posts.reload
    render :index
  end

  def approve
    params[:approve] = PostEvaluation::OPTIONS[:approve]
    @evaluation = PostEvaluation.where('user_id = ? and post_id = ?',
      params[:user_id], params[:post_id]).first

    if @evaluation.nil?
      @evaluation = PostEvaluation.new(params)
      @evaluation.save
    else
      @evaluation.update_attributes(params)
    end

    redirect_to post_path(params[:post_id]),
      :notice => 'Seu voto foi computado com sucesso.'
  end

  def reprove
    params[:approve] = PostEvaluation::OPTIONS[:reprove]
    @evaluation = PostEvaluation.where('user_id = ? and post_id = ?',
      params[:user_id], params[:post_id]).first

    if @evaluation.nil?
      @evaluation = PostEvaluation.new(params)
      @evaluation.save
    else
      @evaluation.update_attributes(params)
    end

    redirect_to post_path(params[:post_id]),
      :notice => 'Seu voto foi computado com sucesso.'
  end

  def abstention
    params[:approve] = PostEvaluation::OPTIONS[:abstention]
    @evaluation = PostEvaluation.where('user_id = ? and post_id = ?',
        params[:user_id], params[:post_id]).first

    if @evaluation.nil?
      @evaluation = PostEvaluation.new(params)
      @evaluation.save
    else
      @evaluation.update_attributes(params)
    end

    redirect_to post_path(params[:post_id]),
      :notice => 'Seu voto foi computado com sucesso.'
  end

  protected

  def check_user
    if current_user.id.to_s != params[:user_id]
      render :nothing => true and return
    end
  end

  def set_return_to_admin_url
    previous_url = request.referrer
    admin_post_path = '/admin/post'

    if previous_url and previous_url.match(admin_post_path)
      session[:return_to_admin_url] = previous_url
    end
  end
end

app/views/posts/_posts.html.erb
<% unless posts.empty? %>
  <ul class="posts">
    <% posts.each do |p| %>
      <li>
        <div class="thumb">
          <a href="<%= post_path(p.id) %>">
            <% if (not p.blog.nil? and p.blog.image?) %>
              <%= image_tag p.blog.image.url(:thumb), :alt => p.title,
                :size => '150x150' %>
            <% else %>
              <%= image_tag '/assets/liberdadebr_blog_thumb.png',
                :alt => p.title, :size => '150x150' %>
            <% end %>
          </a>
        </div>

        <div class="post_info">
          <h3><%= link_to p.title, post_path(p.id) %></h3>

          <p class="info">
            <%= "#{p.blog.name} | " if p.blog %>
            <%= localize (p.approved_at), :format => 'publicado em %d de %B de %Y' %>.
          </p>

          <% if p.content %>
            <div class="resume">
              <p><%= smart_truncate(p.content, 200) %></p>
            </div>
          <% end %>

          <% if p.blog %>
            <p class="links">
              <%= link_to'Visitar o blog', p.blog.link, :target => '_blank' %> |
              <%= link_to'Mais posts deste blog', posts_blog_path(p.blog) %>
            </p>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/posts/_search_form.html.erb
<%= search_form_for search,:html => {
  :class => 'simple_form search_form' } do |f| %>
  <div class="fields">
    <div class="input">
      <%= f.label :title_or_content_or_blog_name_or_authors_name_cont,
        'Buscar' %>
      <%= f.text_field :title_or_content_or_blog_name_or_authors_name_cont,
        :placeholder => 'Busque por blog, autor, título do post ou conteúdo',
        :id => 'search_text' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Buscar' %>
  </div>
<% end %>

app/views/posts/abstention.js.erb
$('#abstention_post').addClass('choosen');
$('#abstention_post').removeClass('choosen');

app/views/posts/approve.js.erb
$('#approve_post').addClass('choosen');
$('#reprove_post').removeClass('choosen');

app/views/posts/index.html.erb
<%= content_for :page_title do 'Posts' end %>

<%= content_for :page_id do 'posts' end %>

<%= content_for :content do %>
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content_shadow"></div>
    <div id="content_gradiente"></div>

    <div id="content">

      <div id="main_content">
        <%= render :partial => 'search_form', :locals => { :search => @search } %>

        <%= render :partial => 'posts', :locals => { :posts => @posts } %>

        <hr />

        <%= paginate @posts, :window => 2 %>
      </div>

      <div id="sidebar">
        <%= render :partial => 'widgets/send_post' %>
        <%= render :partial => 'widgets/facebook_likebox' %>
        <%= render :partial => 'widgets/twitter' %>
      </div>
    </div>
  </div>
  <!-- CONTENT END -->
<% end %>

app/views/posts/new.html.erb
<%= content_for :page_title do @page.title end %>

<%= content_for :page_id do 'send_post' end %>

<%= content_for :content do %>
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content_shadow"></div>
    <div id="content_gradiente"></div>

    <div id="content">
      <div id="content_header">
        <ul class="breadcrumbs">
          <li><%= link_to 'Início', root_path %></li>
          <li><span>Enviar artigo</span></li>
        </ul>

        <hr />

        <div class="header">
          <h2><%= @page.title %></h2>
        </div>
      </div>

      <div id="main_content">
        <%= tinymce_assets %>
        <script type="text/javascript">
          tinyMCE.init({
              mode: 'textareas',
              language: 'br',
              theme: 'advanced',
              theme_advanced_buttons1 : 'bold,italic,underline,|,bullist,numlist,|,link,unlink',
              theme_advanced_toolbar_location: 'top',
              theme_advanced_toolbar_align: 'left',
              theme_advanced_statusbar_location : 'none',
          });
        </script>

        <%= simple_form_for(@post, :url => send_post_path) do |f| %>
          <%= content_tag(:p, notice, :class => 'notice') if notice %>

          <div class="inputs">
            <%= f.input :title %>
            <%= f.input :content, :as => :text %>
            <%= f.input :authors, :label => 'Nomes dos autores',
              :hint => 'Separados por vírgula',
              :input_html => { :value => @authors_input_value } %>
            <%= f.input :categories, :label => 'Categorias',
              :hint => 'Separadas por vírgula',
              :input_html => { :value => @categories_input_value } %>
            <%= recaptcha_tags :display => {:theme => 'red' , :tabindex => '8' } %>
            <% if @recaptcha_error.present? %>
              <div class="input"><span class="error"><%= @recaptcha_error %></span></div>
            <% end %>
          </div>
          <div class="actions">
            <p class="buttom"><%= f.button :submit, 'Enviar' %></p>
          </div>
        <% end %>
      </div>

      <div id="sidebar">
        <div class="post">
          <%= @page.content.html_safe if @page.content %>
        </div>

        <div class="sidebar_detail"></div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/reprove.js.erb
$('#reprove_post').addClass('choosen');
$('#approve_post').removeClass('choosen');

app/views/posts/show.html.erb
<%= content_for :og do %>
  <meta property="og:type" content="article" />
  <meta property="og:title" content="<%= @post.title %>" />
  <meta property="og:site_name" content="<%= configuration.site_title %>" />
  <meta property="og:description" content="<%= smart_truncate(@post.content, 150) %>" />
  <meta property="og:url" content="<%= request.url %>" />
  <meta property="og:image" content="<%= configuration.site_url + '/assets/facebook_size_logo.jpg' %>" />
<% end %>

<%= content_for :page_title do @post.title end %>

<%= content_for :page_id do 'post' end %>

<% if current_user %>
  <%= content_for :moderator_actions do %>
    <div class="rates">
      <p class="approval" style="width: <%= @post.approval_rate.to_i %>%"><%= @post.approval_rate.to_i %>%</p>
      <p class="reproval" style="width: <%= @post.reproval_rate.to_i %>%"><%= @post.reproval_rate.to_i %>%</p>
      <p class="abstention" style="width: <%= @post.abstention_rate.to_i %>%"><%= @post.abstention_rate.to_i %>%</p>
    </div>

    <ul class="actions">
      <li class="buttom">
        <%= link_to 'Aprovar', approve_post_path(@post, current_user),
          :method => :post,
          :class => ('active' if @voted_approve == PostEvaluation::OPTIONS[:approve]),
          :id => 'approve_post' %>
      </li>

      <li class="buttom">
        <%= link_to 'Reprovar', reprove_post_path(@post, current_user),
        :method => :post,
        :class => ('active' if @voted_approve == PostEvaluation::OPTIONS[:reprove]),
        :id => 'reprove_post' %>
      </li>

      <li class="buttom">
        <%= link_to 'Abster-se', abstention_post_path(@post, current_user),
        :method => :post,
        :class => ('active' if @voted_approve == PostEvaluation::OPTIONS[:abstention]),
        :id => 'abstention_post' %>
      </li>

      <li class="buttom"><%= link_to 'Voltar para administração', session[:return_to_admin_url] || '/admin/post' %></li>
    </ul>
  <% end %>
<% end %>

<%= content_for :content do %>
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content_shadow"></div>
    <div id="content_gradiente"></div>

    <div id="content">
      <div id="content_header">
        <ul class="breadcrumbs">
          <li><%= link_to 'Início', root_path %></li>
          <li><%= link_to 'Posts', posts_path %></li>
          <% if @post.blog %>
            <li><%= link_to @post.blog.name, posts_blog_path(@post.blog) %></li>
          <% end %>
          <li><span><%= truncate(@post.title, :length => 80) %></span></li>
        </ul>

        <hr />

        <div class="header">
          <h2><%= @post.title %></h2>

          <p class="info">
            Publicado originalmente em:
            <% if @post.blog %>
              <%= link_to @post.blog.name, @post.blog.link, :target => '_blank',
                :class => 'blog_name' %> |
            <% end %>
            <%= localize (@post.published_at), :format => '%d de %B de %Y' %>.

            <% unless (authors = @post.authors).empty? %>
              <br />
              Por <%= (authors.collect { |a| link_to(a.name, posts_author_path(a)) }).
                to_sentence.html_safe %>.
            <% end %>
          </p>

          <!-- AddThis Button BEGIN -->
          <div class="addthis_toolbox addthis_default_style " addthis:url="<%= request.url %>" addthis:title="<%= @post.title %>">
            <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
            <a class="addthis_button_tweet"></a>
            <a class="addthis_counter addthis_pill_style"></a>
          </div>
          <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
          <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-502149e70cee4a2b"></script>
          <!-- AddThis Button END -->
        </div>
      </div>

      <div id="main_content">
        <div class="post">
          <% if @post.hilight %>
            <div class="hilight_wrapper">
              <p class="hilight"><%= @post.hilight %></p>
            </div>
          <% end %>

          <%= @post.content.html_safe if @post.content %>
        </div>

        <% unless @post.categories.empty? %>
          <div class="post_categories">
            <h3>Categorias</h3>

            <p><%= (@post.categories.collect { |c| link_to(c.name, posts_category_path(c)) }).
              to_sentence.html_safe %></p>
          </div>
        <% end %>

        <hr />

        <div class="fb-comments" data-href="<%= request.url %>" data-num-posts="2" data-width="530"></div>
      </div>

      <div id="sidebar">
        <%= render :partial => 'widgets/advertising' %>
        <%= render :partial => 'widgets/facebook_likebox' %>
        <%= render :partial => 'widgets/twitter' %>
        <%= render :partial => 'widgets/posts' %>
        <%= render :partial => 'widgets/blog', :locals => { :blog => @post.blog } %>
      </div>
    </div>
  </div>
  <!-- CONTENT END -->

<% end %>