config/routes.rb
# -*- encoding : utf-8 -*-

LiberdadeBr::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

#= 1. user routes ==============================================================
  devise_for :users

#= 2. pages ====================================================================
  get "/contato" => "site#contact", :as => :contact
  post "/contato" => "site#send_contact", :as => :send_contact
  get '/about' => 'site#about', :as => :about
  get '/faq' => 'site#faq', :as => :faq
  get '/financers' => 'site#financers', :as => :financers

#= 3. Post evaluation routes ===================================================
  post "/admin/post/:post_id/approve/:user_id" => "posts#approve", :as => :approve_post
  post "/admin/post/:post_id/reprove/:user_id" => "posts#reprove", :as => :reprove_post
  post "/admin/post/:post_id/abstention/:user_id" => "posts#abstention", :as => :abstention_post

#= 4. Author ===================================================================
  get '/posts/author/:id' => 'posts#per_author', :as => :posts_author

#= 5. Blog =====================================================================
  get '/posts/blog/:id' => 'posts#per_blog', :as => :posts_blog

#= 6. Category =================================================================
  get '/posts/category/:id' => 'posts#per_category', :as => :posts_category

#= 7. Post =====================================================================
  resources :posts, :only => [:index, :show, :new]
  post "/posts" => "posts#index", :as => :posts
  post '/posts/send' => 'posts#send_post', :as => :send_post

#= 8. Events and Opportunities =================================================
  get '/eventos-e-oportunidades' => 'site#events_and_opportunities', :as => :events_and_opportunities

#= 9. Events ===================================================================
  get '/eventos' => 'events#index', :as => :events
  get '/evento/:id' => 'events#show', :as => :event

#= 10. Opportunities ===========================================================
  get '/oportunidades' => 'opportunities#index', :as => :opportunities
  get '/oportunidade/:id' => 'opportunities#show', :as => :opportunity

#= 11. Feed ====================================================================
  get '/feed' => 'posts#feed', :as => :feed, :defaults => { :format => 'atom' }

#= 12. Donate ==================================================================
  get '/doacao' => 'site#donate', :as => :donate

  root :to => 'site#index'
end

app/views/layouts/_donate_box.html.erb
<style type="text/css">
  ul#main_navigation .navigation_box .progress_bar .bar span {
    width: <%= (configuration.donation_collected * 200 / configuration.donation_goal).to_i %>px
  }
</style>

<div class="navigation_box_wrapper">
  <div class="navigation_box">
    <div class="content">
      <p><%= configuration.donation_text %></p>

      <hr />

      <div class="progress_bar">
        <p class="bar"><span></span></p>
        <p class="goal">
          <span><%= number_to_currency(configuration.donation_goal) %></span>
        </p>
        <p class="collected"><span>
          <%= number_to_currency(configuration.donation_collected) %>
        </span></p>
      </div>

      <hr />

      <p class="buttom"><%= link_to 'Faça uma doação', donate_path %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Liberdade.br - <%= yield :page_title %></title>

  <%= auto_discovery_link_tag :atom, feed_url %>
  <%= auto_discovery_link_tag :rss, feed_url(:format => 'rss') %>

  <meta content="http://algorich.com.br" name="author" />
  <meta http-equiv="X-UA-Compatible" content="IE=9" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <% unless configuration.keywords.blank? %>
    <meta content="<%= configuration.keywords %>" name="keywords" />
  <% end %>

  <% unless configuration.description.blank? %>
    <meta content="<%= configuration.description %>" name="description" />
  <% end %>

  <%= favicon_link_tag %>

  <% unless yield(:og).blank? %>
    <%= yield :og %>
  <% else %>
    <meta property="og:title" content="<%= configuration.site_title %>" />
    <meta property="og:description" content="<%= configuration.description %>" />
    <meta property="og:url" content="<%= request.url %>" />
    <meta property="og:image" content="<%= configuration.site_url + '/assets/facebook_size_logo.jpg' %>" />
  <% end %>
  <meta property="fb:app_id" content="508974272450177" />

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

  <%= stylesheet_link_tag 'application.css' %>
  <%= javascript_include_tag 'application.js' %>
  <%= csrf_meta_tag %>

  <% if configuration.google_analytics %>
    <script type="text/javascript">
      <%= configuration.google_analytics.html_safe %>
    </script>
  <% end %>

  <!--[if IE 9]>
  <style type="text/css">
    #header_wrapper {
      background-color: transparent !important;
      background-image: none !important;
    }

    #content_shadow, #content_gradiente {
        display: none;
    }

    #content {
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.8);
    }
  </style>
  <![endif]-->

</head>

<body id="<%= yield :page_id %>_page" <%= 'class="logged"'.html_safe if current_user %>>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=508974272450177";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<div id="wrapper">

  <!-- MODERATOR ACTIONS BEGIN -->
  <div id="moderator_actions">
    <%= yield :moderator_actions %>
  </div>
  <!-- MODERATOR ACTIONS END -->

  <!-- HEADER BEGIN -->
  <div id="header_wrapper">
    <div id="header">
      <h1><%= link_to image_tag('/assets/logo.png', :alt => 'Liberdade.br',
        :size => '300x105'), root_path %></h1>
      <% financers_page = Page.get_page(:financers) %>
      <% if financers_page and financers_page.published? %>
        <%= link_to 'Veja a lista completa das pessoas que financiaram esta iniciativa', financers_path, :id => 'partners_page_link' %>
      <% end %>
    </div>
  </div>
  <!-- HEADER END -->

  <!-- MAIN NAVIGATION BEGIN -->
  <div id="main_navigation_wrapper">
    <ul id="main_navigation">
      <% li_class = (request.path == root_path) ? 'active' : '' %>
      <li class="home_item <%= li_class %>">
        <%= link_to '<strong><span>Principal</span></strong>'.html_safe, root_path %>
      </li>

      <% about_page = Page.get_page(:about) %>
      <% if about_page and about_page.published? %>
        <% li_class = (request.path == about_path) ? 'active' : '' %>
        <li class="info_item <%= li_class %>">
          <%= link_to "<strong><span>#{about_page.title}</span></strong>".html_safe, about_path %>
        </li>
      <% end %>

      <% faq_page = Page.get_page(:faq) %>
      <% if faq_page and faq_page.published? %>
        <% li_class = (request.path == faq_path) ? 'active' : '' %>
        <li class="faq_item <%= li_class %>">
          <%= link_to "<strong><span>#{faq_page.title}</span></strong>".html_safe, faq_path %>
        </li>
      <% end %>

      <% li_class = (request.path == events_and_opportunities_path) ? 'active' : '' %>
      <li class="events_item <%= li_class %>">
        <%= link_to '<strong><span>Eventos e oportunidades</span></strong>'.html_safe,
          events_and_opportunities_path %>
      </li>

      <li class="share_item">
        <%= link_to '<strong><span>Divulgue</span></strong>'.html_safe, 'javascript:void(0);' %>

        <div class="navigation_box_wrapper">
          <div class="navigation_box">
            <div class="content">
              <!-- AddThis Button BEGIN -->
              <div class="addthis_toolbox addthis_default_style addthis_32x32_style" addthis:url="<%= configuration.site_url %>" addthis:title="<%= configuration.site_title %>">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_google_plusone_share"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
                <a class="addthis_counter addthis_bubble_style"></a>
              </div>
              <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-501fc6f92d416cf0"></script>
              <!-- AddThis Button END -->
            </div>
          </div>
        </div>
      </li>

      <% donate_page = Page.get_page(:donate) %>
      <% if donate_page and donate_page.published %>
        <li class="donate_item">
          <% if configuration.donation_goal and configuration.donation_collected %>
            <%= link_to "<strong><span>#{donate_page.title}</span></strong>".html_safe,
              'javascript:void(0);' %>

            <%= render :partial => 'layouts/donate_box' %>
          <% else %>
            <%= link_to "<strong><span#{donate_page.title}</span></strong>".html_safe,
              donate_path %>
          <% end %>
        </li>
      <% end %>

      <% contact_page = Page.get_page(:contact) %>
      <% if contact_page and contact_page.published? %>
        <% li_class = (request.path == contact_path) ? 'active' : '' %>
        <li class="contact_item <%= li_class %>">
          <%= link_to "<strong><span>#{contact_page.title}</span></strong>".html_safe, contact_path %>
        </li>
      <% end %>

      <li class="social_item">
        <ul>
          <% unless configuration.facebook.blank? %>
            <li class="facebook_item">
              <%= link_to 'Facebook', configuration.facebook, :target => '_blank' %>
            </li>
          <% end %>
          <% unless configuration.twitter.blank? %>
            <li class="twitter_item">
              <%= link_to 'Twitter', configuration.twitter, :target => '_blank' %>
            </li>
          <% end %>
          <li class="rss_item">
            <%= link_to 'RSS', feed_url %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
  <!-- MAIN NAVIGATION END -->

  <%= yield :banner %>

  <div id="big_content">
    <%= yield :content %>

    <!-- FOOTER BEGIN -->
    <div id="footer_wrapper">
      <div id="footer">
        <% if configuration.footer %>
          <div id="footer_info">
            <%= configuration.footer.html_safe %>
          </div>
        <% end %>

        <ul id="footer_sections">
          <li id="partners_list">
            <h3>Parceiros</h3>

            <ul>
              <% Blog.all.each do |b| %>
                <li><span>
                  <a href="<%= b.link %>" target="_blank"><%= b.name %></a>
                </span></li>
              <% end %>
            </ul>

            <p class="next">Próximo</p>
            <p class="previous">Anterior</p>
          </li>

          <% unless (sponsors = Sponsor.all).empty? %>
            <li id="sponsors_list">
              <h3>Patrocinadores</h3>

              <ul>
                <% sponsors.each do |s| %>
                  <li><span>
                    <% if s.link %>
                      <a href="<%= s.link %>" target="_blank">
                        <% if s.image.exists? %>
                          <%= image_tag s.image.url(:small), :alt => s.name,
                            :size => '315x100' %>
                        <% else %>
                          <%= s.name %>
                        <% end %>
                      </a>
                    <% else %>
                      <% if s.image.exists? %>
                        <%= image_tag s.image.url(:small), :alt => s.name,
                          :size => '315x100' %>
                      <% else %>
                        <%= s.name %>
                      <% end %>
                    <% end %>
                  <% end %>
                </span></li>
              </ul>

            </li>
          <% end %>

          <% if configuration.realization_image %>
            <li id="implementation">
              <h3>Realização</h3>

              <ul>
                <li><%= link_to image_tag(configuration.realization_image.url(:normal), :alt => configuration.realization_title, :size => '250x56'),
                  configuration.realization_url, :target => '_blank' %></li>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>

        <!-- <p id="algorich">
          <a class="alg_logo alg_logo_wb" href="http://www.algorich.com.br/" target="_blank">
          <img src="http://media.algorich.com.br/web_algorich_logo_hor.png" alt="Algorich" width="121" height="28"><br />
          Desenvolvido pela Algorich
        </a></p> -->
      </div>
    </div>
    <!-- FOOTER END -->
  </div>

</div>
</body>

</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>

<html lang="pt-BR">

<head>
  <title>Liberdade.br - Login</title>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta content='http://algorich.com.br' name='author' />

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

  <%= stylesheet_link_tag 'login.css' %>

  <%= csrf_meta_tag %>
</head>

<body id="login_page">
<div id="wrapper">
  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content">
      <%= yield :content %>
    </div>
  </div>
  <!-- CONTENT END -->
</div>
</body>

</html>